FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Scenariusze będą montowane wolumenem ./scenarios:/app/scenarios
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "65432"]
